GAbasdat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('silauaja.urls')),
    path('taskijo/', include('taskIjo.urls')),
    path('taskmerah/', include('taskMerah.urls')),
    path('taskbiru/', include('taskBiru.urls')),
    path('taskkuning/', include('taskKuning.urls'))
]

taskIjo/urls.py
from django.urls import path
from . import views

app_name = 'taskIjo'

urlpatterns = [
    path('laundry_list/',views.laundrylist, name ='laundrylist'),
    path('create_laundry_list/',views.createLaundryList, name='createlaundrylist'),
    path('update_laundry_list/',views.updateLaundryList, name='updatelaundrylist'),
    path('item/', views.item, name='item'),
    path('create_item/', views.createItem, name='createitem'),
    path('delete_laundry', views.deleteLaundryList, name='deletelaundrylist'),
    # path('update_deliver_cost', views.updateDeliveryCost, name='updateDeliveryCost'),
    # path('create_deliver_cost', views.updateDeliveryCost, name='createeDeliveryCost'),
]

taskKuning/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('updateDeliveryCost/',views.updateDeliveryCost, name ='updateDeliveryCost'),
    path('create_topup_dpay/',views.create_delivery, name='createdelivery'),
]

templates/3.html

<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        table,td,th{
            border: 1px solid black;
        }
    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laundry List</title>
</head>
<body>
    <h1 style="text-align: center;">DPAY TOPUP</h1>
    <table style="width: 100%;">
        <tr>
            <th>No</th>
            <th>Status Code</th>
            <th>Status Name</th>
        </tr>
        <tr>
            <td>1</td>
            <td>OKK</td>
            <td>Done</td>
        </tr>
    </table>
</body>
</html>

templates/4.html

<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        table,td,th{
            border: 1px solid black;
        }
    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laundry List</title>
</head>
<body>
    
    <h1 style="text-align: center;">FORM CREATE TOPUP DPAY TRANSACTION</h1>
    <div style="width: 700px; height: 1000px; margin-left: 40%;">
    <form>
        <label for="cars">Email          :</label>
        <select name="CUSTOMER" id="CUST">
          <option value="csiggins0@epa.gov">csiggins0@epa.gov</option>
        </select>
        <p>Nominal :</p>
        <input type="text" id="lname" name="lname">
    </form>
    </div>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>SILAU</title>
</head>
<body>
    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href=#TODOLOGIN><h5>SILAU</h5></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="#Profile">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Tarif</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Testimonies</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Transaction Status</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Laundry Transaction
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="">Create Laundry Transaction</a>
                <a class="dropdown-item" href="#">Laundry List Transaction</a>
              </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Top Up DPAY
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Create TOP UP Transaction</a>
                    <a class="dropdown-item" href="#">List TOP UP Transaction</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Laundry List
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'taskIjo:createlaundrylist' %}">Create Laundry List</a>
                    <a class="dropdown-item" href="{% url 'taskIjo:updatelaundrylist' %}">Laundry List</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Item
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'taskIjo:createitem' %}">Create Item</a>
                    <a class="dropdown-item" href="{% url 'taskIjo:item' %}">List Item</a>
                </div>
            </li>
          </ul>
        </div>
      </nav>
    <!-- Contents -->
    {% block content %}{% endblock content %}

    <!-- Additional Scripts -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/courierform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        table,td,th{
            border: 1px solid black;
        }
    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Courier Registration</title>
</head>
<body>
    <h1 style="text-align: center;">Courier Registration Form</h1>
    <form>
        <table>
            <tr>
                <th><label for="email">Email:</label></th>
                <td><input name="email" type="email"></td>
            </tr>
            <tr>
                <th><label for="password">Password:</label></th>
                <td><input name="password" type="password"></td>
            </tr>
            <tr>
                <th><label for="fullname">Full Name:</label></th>
                <td><input name="fullname" type="text"></td>
            </tr>
            <tr>
                <th><label for="phone">Phone Number:</label></th>
                <td><input name="phone" type="number"></td>
            </tr>
            <tr>
                <th><label for="gender">Gender:</label></th>
                <td><input name="gender" type="text"></td>
            </tr>
            <tr>
                <th><label for="address">Address:</label></th>
                <td><input name="address" type="text"></td>
            </tr>
            <tr>
                <th><label for="npwp">NPWP:</label></th>
                <td><input name="npwp" type="text"></td>
            </tr>
            <tr>
                <th><label for="account">Account No:</label></th>
                <td><input name="account" type="text"></td>
            </tr>
            <tr>
                <th><label for="bank">Bank:</label></th>
                <td><input name="bank" type="text"></td>
            </tr>
            <tr>
                <th><label for="branch">Branch:</label></th>
                <td><input name="branch" type="text"></td>
            </tr>
            <tr>
                <th><label for="sim">SIM No:</label></th>
                <td><input name="sim" type="text"></td>
            </tr>
            <tr>
                <th><label for="vehicleno">Vehicle No:</label></th>
                <td><input name="vehicleno" type="text"></td>
            </tr>
            <tr>
                <th><label for="vehicletype">Vehicle Type:</label></th>
                <td><input name="vehicletype" type="text"></td>
            </tr>
        </table>
        <input type="submit" value="submit">
    </form>
</body>
</html>

templates/createItem.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <h1 style="text-align: center;">FORM ITEM</h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            <tr>
                <th><label >Item Code:</label></th>
                <td>{{form.code}}</td>
            </tr>
            <tr>
                <th><label >Item Name:</label></th>
                <td>{{form.name}}</td>
            </tr>
        </table>
        <input class="btn btn-outline-primary" type="submit" value="Create">
    </form>
{% endblock %}

templates/deliveryCost.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        table,td,th{
            border: 1px solid black;
        }
    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laundry List</title>
</head>
<body>
    <h1 style="text-align: center;">DELIVERY COST</h1>
    <table style="width: 100%;">
        <tr>
            <th>Code</th>
            <th>Min Distance</th>
            <th>Max Distance</th>
            <th>Price</th>
            <th>Action</th>
        </tr>
        <tr>
            <td>S</td>
            <td>0</td>
            <td>3</td>
            <td>5000</td>
            <td>
                <a href="{% url 'taskIjo:updateDeliveryCost' %}"><button type="button">Update</button></a><br>
                <button type="button">Delete</button>
            </td>
        </tr>
        <tr>
            <td>L</td>
            <td>3</td>
            <td>10</td>
            <td>10000</td>
            <td>
                <a href="{% url 'taskIjo:updateDeliveryCost' %}"><button type="button">Update</button></a><br>
                <button type="button">Delete</button>
            </td>
        </tr>
    </table>
</body>
</html>

templates/deliveryCostForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laundry List Form</title>
</head>
<body>
    <h1 style="text-align: center;">PICKUP AND DELIVERY COST FORM</h1>
    <form>
        <label for="email">Code</label>
        <input type="text" name="email"><br>
        <label for='minDistance'>Min Distance:</label>
        <input type="number" name="minDistance"><br>
        <label for='maxDistance'>Max Distance:</label>
        <input type="number" name="maxDistance"><br>
        <label for='Price'>Price:</label>
        <input type="number" name="maxDistance"><br>
    </form>
</body>
</html>

templates/laundryForm.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <h1 style="text-align: center;">LAUNDRY LIST FORM</h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            <tr>
                <th><label >Item</label></th>
                <td>{{form.email}}</td>
            </tr>
            <tr>
                <th><label >Item Amount:</label></th>
                <td>{{form.item_amount}}</td>
            </tr>
            <tr>
                <th><label >Item Code:</label></th>
                <td>{{form.item_code}}</td>
            </tr>
        </table>
        <input class="btn btn-outline-primary" type="submit" value="Create">
    </form>
{%endblock%}

templates/login.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <h1 style="text-align: center;">LOGIN</h1>
    <table>
        <tr>
            <th><label for="email">Email:</label></th>
            <td><input name="email" type="email"></td>
        </tr>
        <tr>
            <th><label for="password">Password:</label></th>
            <td><input name="password" type="password"></td>
        </tr>
    </table>
    <input type="submit" value="submit">
{% endblock %}

templates/stafform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        table,td,th{
            border: 1px solid black;
        }
    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Staff Registration</title>
</head>
<body>
    <h1 style="text-align: center;">Staff Registration Form</h1>
    <form>
        <table>
            <tr>
                <th><label for="email">Email:</label></th>
                <td><input name="email" type="email"></td>
            </tr>
            <tr>
                <th><label for="password">Password:</label></th>
                <td><input name="password" type="password"></td>
            </tr>
            <tr>
                <th><label for="fullname">Full Name:</label></th>
                <td><input name="fullname" type="text"></td>
            </tr>
            <tr>
                <th><label for="phone">Phone Number:</label></th>
                <td><input name="phone" type="number"></td>
            </tr>
            <tr>
                <th><label for="gender">Gender:</label></th>
                <td><input name="gender" type="text"></td>
            </tr>
            <tr>
                <th><label for="address">Address:</label></th>
                <td><input name="address" type="text"></td>
            </tr>
            <tr>
                <th><label for="npwp">NPWP:</label></th>
                <td><input name="npwp" type="text"></td>
            </tr>
            <tr>
                <th><label for="account">Account No:</label></th>
                <td><input name="account" type="text"></td>
            </tr>
            <tr>
                <th><label for="bank">Bank:</label></th>
                <td><input name="bank" type="text"></td>
            </tr>
        </table>
        <input type="submit" value="submit">
    </form>
</body>
</html>

templates/testimony.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        table,td,th{
            border: 1px solid black;
        }
    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Testimony</title>
</head>
<body>
    <h1 style="text-align: center;">TESTIMONY
    </h1>
    <table style="width: 100%;">
        <tr>
            <th>Email</th>
            <th>Date Transaksi</th>
            <th>Testimony</th>
            <th>Rating</th>
        </tr>
        <tr>
            <td>csiggins0@epa.gov</td>
            <td>07/08/2020</td>
            <td>Lorem ipsum jamet</td>
            <td>5</td>
            <td>
                <a href=""><button type="button">Update</button></a><br>
                <button type="button">Delete</button>
            </td>
        </tr>
    </table>
</body>
</html>

templates/testimony_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Testimony Form</title>
</head>
<body>
    <h1 style="text-align: center;">TESTIMONY FORM</h1>
    <form>
        <label for="email">Email:</label>
        <select id="email" name="email">
            <option value="csiggins0@epa.gov">csiggins0@epa.gov</option>
        </select><br>
        <label for='transactionDate'>Transaction Date:</label>
        <input type="date" name="transactionDate"><br>
        <label for='testimony'>Testimony:</label>
        <input type="text" name="testimony"><br>
        <label for='rating'>Rating:</label>
        <select id="rating" name="rating">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option> 
        </select><br>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/updateLaundryList.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <h1 style="text-align: center;">FORM UPDATE LAUNDRY LIST</h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            <tr>
                <th><label >Email</label></th>
                <td>{{form.email}}</td>
            </tr>
            <tr>
                <th><label >Transaction Date:</label></th>
                <td>{{form.transaction_date}}</td>
            </tr>
            <tr>
                <th><label >Serial Number:</label></th>
                <td>{{form.serial_no}}</td>
            </tr>
            <tr>
                <th><label >Item Amount:</label></th>
                <td>{{form.item_amount}}</td>
            </tr>
            <tr>
                <th><label >Item Code:</label></th>
                <td>{{form.item_code}}</td>
            </tr>
        </table>
        <input class="btn btn-outline-primary" type="submit" value="Create">
    </form>
{%endblock%}

templates/update_service_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Service Form</title>
</head>
<body>
    <h1 style="text-align: center;">UPDATE SERVICE FORM</h1>
    <form>
        <label for="code">Code [disable]:</label>
        <select id="code" name="code">
            <option value="RG">RG</option>
        </select><br>
        <label for='name'>Name:</label>
        <input type="text" name="name"><br>
        <label for='duration'>Duration:</label>
        <input type="text" name="duration"><br>
        <label for='price'>Price:</label>
        <input type="number" name="price"><br>
        <input type="submit" value="Submit">
    </form>
</body>
</html>